include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - package
  - test-package
  - deploy

.docker-operations-build:
  variables:
    PARENT_IMAGE_NAME: redmic/docker-index-pages
    PARENT_IMAGE_TAG: v1.0.0
    DOCKER_BUILD_ARGS: --build-arg PARENT_IMAGE_NAME=${PARENT_IMAGE_NAME} --build-arg PARENT_IMAGE_TAG=${PARENT_IMAGE_TAG}

.deploy:
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    COMPOSE_FILE: docker-compose.yml
    STACK: index
    DD_IMAGE_NAME: ${CI_REGISTRY_IMAGE}
    DD_IMAGE_TAG: ${CI_COMMIT_SHA}
    SERVICES_TO_CHECK: index_${CI_PROJECT_NAME}
    STATUS_CHECK_DELAY: 60
  environment:
    url: https://index.${PUBLIC_HOSTNAME}
