include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/_deployment.yml'

stages:
  - package
  - test-package
  - deploy

.docker-operations-build:
  variables:
    PARENT_IMAGE_NAME: redmic/docker-index-pages
    PARENT_IMAGE_TAG: v1.0.0
    DOCKER_BUILD_ARGS: --build-arg PARENT_IMAGE_NAME=${PARENT_IMAGE_NAME} --build-arg PARENT_IMAGE_TAG=${PARENT_IMAGE_TAG}

.deploy:
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    STACK: index
    SERVICES_TO_CHECK: index_${CI_PROJECT_NAME}
    STATUS_CHECK_DELAY: 60
    DD_IMAGE_NAME: ${CI_REGISTRY_IMAGE}
    DD_IMAGE_TAG: ${CI_COMMIT_SHA}
    DD_PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
  environment:
    name: dev
    url: https://index.${DEV_PUBLIC_HOSTNAME}

deploy-support-branch-development:
  extends: .deploy
  only:
    - branches
  except:
    - master
    - schedules

deploy-stable-branch-development:
  extends: .deploy
  only:
    - master
  except:
    - schedules

deploy-version-development:
  extends: .deploy
  only:
    - tags
